embedding Hibernate in the DAO layer.
Ivantus1988/shop-app pull request #5
Opened 2023-06-12 08:36 UTC by Ivantus1988

embedding Hibernate

2023-06-12 21:15 UTC, GrigoryPopravko requested changes

2023-06-12 21:15 UTC, GrigoryPopravko commented on database/src/main/java/com/shukalovich/database/entity/FactoryEntity.java
> +public class FactoryEntity implements BaseEntity<Long>{
BaseEntity<Long>{ - нет пробела перед скобкой, не пройдет чекстайл

2023-06-12 21:15 UTC, GrigoryPopravko commented on database/src/main/java/com/shukalovich/database/entity/ProductEntity.java
> +public class ProductEntity implements BaseEntity<Long>{
нет пробела перед скобкой, не пройдет чекстайл

2023-06-12 21:15 UTC, GrigoryPopravko commented on database/src/main/java/com/shukalovich/database/entity/UserEntity.java
> +public class UserEntity extends CreatableEntity implements BaseEntity<Long>{
нет пробела перед скобкой, не пройдет чекстайл

2023-06-12 21:15 UTC, GrigoryPopravko commented on database/src/main/java/com/shukalovich/database/entity/OrderEntity.java
> +@ToString(exclude = "products")
нету свойства "products", есть "product"

2023-06-12 21:15 UTC, GrigoryPopravko commented on database/src/test/java/com/shukalovich/database/dao/UserDaoTest.java
> +        session.getTransaction().commit();
Два теста вместе не проходят у тебя.

2023-06-13 11:07 UTC, Ivantus1988 commented on database/src/main/java/com/shukalovich/database/entity/FactoryEntity.java
> +public class FactoryEntity implements BaseEntity<Long>{
исправил

2023-06-13 11:09 UTC, Ivantus1988 commented on database/src/main/java/com/shukalovich/database/entity/ProductEntity.java
> +public class ProductEntity implements BaseEntity<Long>{
исправил

2023-06-13 11:09 UTC, Ivantus1988 commented on database/src/main/java/com/shukalovich/database/entity/UserEntity.java
> +public class UserEntity extends CreatableEntity implements BaseEntity<Long>{
испарвил

2023-06-13 11:09 UTC, Ivantus1988 commented on database/src/main/java/com/shukalovich/database/entity/UserEntity.java
> +public class UserEntity extends CreatableEntity implements BaseEntity<Long>{
исправил

2023-06-15 07:42 UTC, GrigoryPopravko approved these changes

2023-06-15 09:06 UTC, merged